### ISSUE TITLE
Revive and support this project

### ISSUE THREAD

**Issue by jasny** [tdegrunt/mongodb-rest#44]
@tdegrunt I noticed that this project is abandoned. Is it possible for us to revive it and take control? We'd revise the code, but the funtionality would remain. Additionally we would add JSONSchema validation and Elastic Search support.

You can contact me via e-mail at arnold@jasny.net (:netherlands:).

**Comment by tdegrunt** [comment]
Someone did, see: https://github.com/ashleydavis/mongodb-rest
However, that also stopped 3 years ago. 

We could continue here, or in a separate org which I created at some point (https://github.com/mongodb-rest). Seems you're Dutch, me too. My email is in package.json.
Coincidentally I also wrote https://github.com/tdegrunt/jsonschema 

Long term that seems better than ping-ponging the project around?

**Comment by jasny** [comment]
@ashleydavis Great. Better though, if the effort you put into the fork would make it back upstream.

@tdegrunt Creating a group just for this one repository seems silly. As an alternative, what do you think about a 'json-schema-js' organization, with a number of projects including tdegrunt/jsonschema?

I talked to @tchapi earlier about his 'jsonform' project. I'm positive he'd join this organization and move his project there.
